import { escapeHtml } from './utils.js';

const fmt = (date) => date ? new Date(date).toLocaleString('en-US', { timeZone: 'America/Los_Angeles', dateStyle: 'short', timeStyle: 'short' }) : '-';
const selected = (value, expected) => value === expected ? 'selected' : '';

export function renderDashboard({ settings, queues, contacts, csrf, notice = '' }) {
  const rows = queues.map((q) => {
    const c = q.contacts;
    const t = q.followup_templates;
    return `<tr><td>${escapeHtml(c.first_name || 'Unknown')}<small>${escapeHtml(c.platform)} · stage ${c.current_stage}</small></td><td>#${q.stage} ${escapeHtml(t.label)}<small>${escapeHtml(t.body)}</small></td><td>${fmt(q.scheduled_for)}</td><td><span class="tag ${q.status}">${escapeHtml(q.status)}</span>${q.last_error ? `<small>${escapeHtml(q.last_error)}</small>` : ''}</td><td><form method="post"><input type="hidden" name="csrf" value="${csrf}"><input type="hidden" name="queue_id" value="${q.id}"><button name="action" value="approve">Approve</button><button name="action" value="send">Send now</button><button class="muted" name="action" value="skip">Skip stage</button></form></td></tr>`;
  }).join('') || '<tr><td colspan="5" class="empty">No follow-ups waiting.</td></tr>';
  const contactRows = contacts.map((c) => `<tr><td>${escapeHtml(`${c.first_name || ''} ${c.last_name || ''}`.trim() || c.platform_user_id)}</td><td>${escapeHtml(c.platform)}</td><td>${c.current_stage}/10</td><td>${escapeHtml(c.status)}</td><td>${fmt(c.last_customer_at)}</td><td><form method="post"><input type="hidden" name="csrf" value="${csrf}"><input type="hidden" name="contact_id" value="${c.id}"><select name="status">${['active','replied','waiting','paused','booked','opted_out','completed'].map(s=>`<option ${selected(c.status,s)}>${s}</option>`).join('')}</select><button name="action" value="contact_status">Save</button></form></td></tr>`).join('');
  return `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>MaidThis Follow-ups</title><style>
  :root{font-family:Inter,system-ui,sans-serif;color:#18212f;background:#f4f7fb}body{margin:0}.wrap{max-width:1280px;margin:auto;padding:28px}h1{margin:0 0 4px}.sub,small{color:#64748b}small{display:block;margin-top:5px;max-width:520px}.cards{display:grid;grid-template-columns:repeat(4,1fr);gap:14px;margin:22px 0}.card,section{background:white;border:1px solid #dbe3ee;border-radius:14px;padding:18px;box-shadow:0 4px 18px #1e293b0a}.value{font-size:26px;font-weight:750}.ok{color:#067647}.danger{color:#b42318}section{margin:18px 0;overflow:auto}table{border-collapse:collapse;width:100%;font-size:14px}th,td{text-align:left;border-bottom:1px solid #edf1f6;padding:12px;vertical-align:top}button,select,input{border:1px solid #cbd5e1;border-radius:7px;padding:8px;background:white;margin:2px}button{background:#1267e5;color:white;border-color:#1267e5;cursor:pointer}.muted{background:white;color:#334155}.tag{display:inline-block;border-radius:999px;padding:4px 8px;background:#eef2ff}.approved{background:#dcfce7}.blocked_policy,.failed{background:#fee2e2}.notice{background:#ecfdf3;color:#065f46;padding:12px;border-radius:10px}.warning{background:#fff7ed;color:#9a3412;padding:12px;border-radius:10px}.settings{display:flex;align-items:end;gap:14px;flex-wrap:wrap}.settings label{display:grid;gap:5px}.empty{text-align:center;padding:30px}.right{margin-left:auto}@media(max-width:800px){.cards{grid-template-columns:1fr 1fr}.wrap{padding:14px}}
  </style></head><body><div class="wrap"><h1>MaidThis Meta Follow-ups</h1><div class="sub">Deterministic stages, reply cancellation, duplicate protection, and policy checks.</div>${notice ? `<p class="notice">${escapeHtml(notice)}</p>` : ''}
  ${!settings.auto_enabled ? '<p class="warning">Global sending is paused. Queues may be created, but no message can send.</p>' : ''}
  <div class="cards"><div class="card"><div class="sub">Sending</div><div class="value ${settings.auto_enabled?'ok':'danger'}">${settings.auto_enabled?'Enabled':'Paused'}</div></div><div class="card"><div class="sub">Mode</div><div class="value">${settings.review_mode?'Review':'Automatic'}</div></div><div class="card"><div class="sub">Daily limit</div><div class="value">${settings.followups_per_day}</div></div><div class="card"><div class="sub">Waiting review</div><div class="value">${queues.filter(q=>q.status==='pending').length}</div></div></div>
  <section><h2>Controls</h2><form method="post" class="settings"><input type="hidden" name="csrf" value="${csrf}"><input type="hidden" name="action" value="settings"><label>Global sending<select name="auto_enabled"><option value="false" ${selected(settings.auto_enabled,false)}>Paused</option><option value="true" ${selected(settings.auto_enabled,true)}>Enabled</option></select></label><label>Mode<select name="review_mode"><option value="true" ${selected(settings.review_mode,true)}>Review required</option><option value="false" ${selected(settings.review_mode,false)}>Automatic</option></select></label><label>Follow-ups per day<input type="number" min="1" max="10" name="followups_per_day" value="${settings.followups_per_day}"></label><label>Minimum gap (minutes)<input type="number" min="15" name="min_gap_minutes" value="${settings.min_gap_minutes}"></label><label>Silence before queueing (minutes)<input type="number" min="15" name="silence_minutes" value="${settings.silence_minutes}"></label><button>Save controls</button></form>
  <form method="post"><input type="hidden" name="csrf" value="${csrf}"><input type="hidden" name="action" value="backfill"><button class="muted">Import existing Meta history</button></form></section>
  <section><h2>Review queue</h2><table><thead><tr><th>Lead</th><th>Next follow-up</th><th>Due (LA)</th><th>Status</th><th>Action</th></tr></thead><tbody>${rows}</tbody></table></section>
  <section><h2>Recent leads</h2><table><thead><tr><th>Lead</th><th>Channel</th><th>Stage</th><th>Status</th><th>Last reply (LA)</th><th>Control</th></tr></thead><tbody>${contactRows}</tbody></table></section>
  </div></body></html>`;
}
